#!/usr/bin/env bash
# create_example_env.sh — generate a sample .env file for InterviewLM.
#
# Usage:
#   backend/create_example_env.sh --local   → creates backend/.env.local
#   backend/create_example_env.sh --prod    → creates backend/.env
#
# Fails if the target file already exists (won't overwrite).

set -euo pipefail

cd "$(dirname "$0")"

die()  { echo "error: $*" >&2; exit 1; }
info() { echo "--- $*"; }

case "${1:-}" in
  --local)
    target="backend/.env.local"
    ;;
  --prod)
    target="backend/.env"
    ;;
  *)
    echo "Usage: create_example_env.sh --local | --prod" >&2
    exit 1
    ;;
esac

if [[ -f "$target" ]]; then
  die "${target} already exists — remove it first if you want a fresh sample"
fi

info "Creating ${target}"

cat >"$target" <<'ENV'
# ---------------------------------------------------------------------------
# InterviewLM environment — generated by create_example_env.sh
# ---------------------------------------------------------------------------

# --- Database (required) ---------------------------------------------------
# Local: the pgvector container started by the README
# Prod:  the Neon pooled URL
DATABASE_URL=postgresql+psycopg://cortex:cortex@127.0.0.1:55432/cortex

# Graph checkpointer — derived by dropping -pooler from DATABASE_URL if unset
# GRAPH_DATABASE_URL=

# --- Model provider (required for real calls) ------------------------------
# Local: leave unset — the fake model runs offline, deterministic, real metering
# Prod:  your OpenRouter key
# OPENROUTER_API_KEY=

# Which model the Interviewer and Judge call
# MODEL=deepseek/deepseek-chat

# --- Embeddings (required for import) --------------------------------------
# hashing  — lexical stand-in, no dependencies, what the test suite runs on
# siglip   — real model, needs: pip install -e "backend[embeddings]"
# http     — external embedding endpoint
EMBEDDING_PROVIDER=hashing

# --- Object store (prod only — local uses disk) ----------------------------
# Uploads go here when set. Without it, documents live on the container
# layer and are lost at the next deploy. The bucket must serve the S3 API.
# CONTENT_BUCKET=
# R2_ENDPOINT_URL=
# R2_ACCESS_KEY_ID=
# R2_SECRET_ACCESS_KEY=

# --- Credits / metering (prod only) ----------------------------------------
# OPENROUTER_POOL_KEY=          # our OpenRouter pool key
# CREDIT_CENTS_PER_TOKEN=       # override if needed

# --- Identity (prod only) --------------------------------------------------
# GATEHOUSE_URL=                # auth host
# GATEHOUSE_API_KEY=

# --- Surface ----------------------------------------------------------------
# Port the API listens on inside the container (host mapping is in deploy.sh)
# PORT=8000

# The surface mount — built frontend/dist, served at /
# SURFACE_DIR=frontend/dist

# --- Misc -------------------------------------------------------------------
# ALLOWED_ORIGINS=              # CORS origins (default: same-origin, none needed)
# LOG_LEVEL=info
ENV

chmod 600 "$target"
info "Done — edit ${target} with your real values"
